name: main

on:
  push:
    branches: [master]

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run install
        run: make install
        env:
          ZSH_VERSION: 5.8
          ZSH_CACHE_DIR: ${GITHUB_WORKSPACE}/.oh-my-zsh/cache
